"""add saved_routes table

Revision ID: e53a3e77c98c
Revises: 560952c53357
Create Date: 2026-05-18 16:07:47.349440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53a3e77c98c'
down_revision: Union[str, Sequence[str], None] = '560952c53357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lon', sa.Float(), nullable=True),
    sa.Column('dest_lat', sa.Float(), nullable=True),
    sa.Column('dest_lon', sa.Float(), nullable=True),
    sa.Column('vehicle', sa.String(), nullable=True),
    sa.Column('green_co2', sa.String(), nullable=True),
    sa.Column('green_dist', sa.String(), nullable=True),
    sa.Column('green_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_routes_id'), 'saved_routes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_routes_id'), table_name='saved_routes')
    op.drop_table('saved_routes')
    # ### end Alembic commands ###
